apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  smtp-username: "aGFidWZmYWxvNTZAZ21haWwuY29t"
  smtp-password: "cHRudSBtb3ZyIHBzcGIgcW1xcg=="
  mongodb-password: "eGxPN1dFazMzZjY1RHNkcg=="
